### ISSUE TITLE
Should we allow for draining any remaining balance if the collateral is insufficient?

### ISSUE THREAD

**Issue by aasseman** [semiotic-ai/timeline-aggregation-protocol-contracts#5]
Should we allow for draining any remaining balance if the collateral is insufficient?

_Originally posted by @aasseman in https://github.com/semiotic-ai/timeline-aggregation-protocol-contracts/pull/4#discussion_r1224937813_

**Comment by That3Percent** [comment]
There are some tradeoffs here. The three options are:
* Remit as much as possible and finish the withdrawal (max withdrawal)
* Remit as much as possible, set a negative account balance and allow the rest to be remitted in the future (partial withdraw)
* Revert the transaction (revert)

For an MVP we should take partial withdrawal off the table. It adds a lot of accounting to the contract and would open up other questions.

My preference then is to go with max withdrawal because Scalar TAP can get performance benefits from "stochastic security" (a term I just made up). There is a performance cost to synchronizing state. So, it can be beneficial for a payee to get loose with collateral checks as long as it bounds losses. With that setup, I can imagine situations like a 3000.0001 GRT payment against 3000 in escrow. In that situation, I think the payee would reasonably rather collect the 3000 GRT than 0 GRT. It may not be possible at that point to get a receipt for <= 3000 GRT if data has been destroyed.

The tradeoff is that if it's something like a 10,000 GRT payment against 100 GRT collateral you probably want to know something is broken, and exceptions (reverts) are a good way of getting attention. Ideally though you would still want to collect the payment... Reverting the transaction doesn't get the payee any closer to collecting the full payment.
